// ④ 入れたか確かめる（assets/js/airreach-verify.js の judge）。架空のページだけ・ネットワークなし
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const ctx = { window: {}, console, URL, JSON, Math, Date };
vm.createContext(ctx);
for (const f of ['airreach-ai3.js', 'airreach-case-steps.js', 'airreach-verify.js']) vm.runInContext(fs.readFileSync(path.join(ROOT, 'assets/js', f), 'utf8'), ctx);
const V = ctx.window.AirReachVerify, K = ctx.window.AirReachCaseSteps;
let pass = 0, fail = 0;
const t = (n, ok, got) => { if (ok) { pass++; console.log('PASS', n); } else { fail++; console.log('FAIL', n, got === undefined ? '' : JSON.stringify(got).slice(0, 400)); } };
const Q = [{ q: '営業時間・定休日を教えてください。', a: '営業時間は 10:00〜19:00 です。定休日は 火曜 です。' }, { q: '料金の目安を教えてください。', a: '料金の例：カット 5,500円〜。詳しくはサイトの料金ページをご覧ください。' }];
const faqLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: Q.map((x) => ({ '@type': 'Question', name: x.q, acceptedAnswer: { '@type': 'Answer', text: x.a } })) };
const orgLd = { '@context': 'https://schema.org', '@type': 'HairSalon', name: '株式会社サンプル', alternateName: 'サンプル美容室 Hana', url: 'https://sample-salon.example/' };
const LLMS = '# サンプル美容室 Hana\n\n> 縮毛矯正\n\n## Primary\n- Home: https://sample-salon.example/\n';
const job = { url: 'https://sample-salon.example/', files: { 'schema/faq.jsonld': JSON.stringify(faqLd), 'schema/organization.jsonld': JSON.stringify(Object.assign({}, orgLd, { '@type': 'Organization' })), 'public/llms.txt': LLMS, 'MANIFEST.json': JSON.stringify({ package_version: '1.3.0' }) } };
const ld = (o) => '<script type="application/ld+json">' + JSON.stringify(o) + '</script>';
const faqHtml = Q.map((x) => '<h3>' + x.q + '</h3>\n<p>' + x.a.replace('10:00〜19:00', '10:00〜19:00 ') + '</p>').join('\n');
const page = (body, extra) => ({ status: 200, html: '<html><head>' + (extra || '') + '</head><body><nav>ホーム</nav>' + body + '</body></html>' });
const state = (r, k) => r.checks.find((c) => c.key === k).state;
let r = V.judge(job, page(faqHtml, ld(faqLd) + ld(orgLd)), { status: 200, text: LLMS });
t('すべて入っている：ok・FAQ 2/2・データ・お店の情報・llms', r.ok && state(r, 'faq_text') === 'ok' && state(r, 'faq_ld') === 'ok' && state(r, 'org') === 'ok' && state(r, 'llms') === 'ok', r.checks);
r = V.judge(job, page('<h3>' + Q[0].q + '</h3><p>' + Q[0].a + '</p>', ld(faqLd) + ld(orgLd)), { status: 200, text: LLMS });
t('1問がページに出ていない：ng・どの質問か', !r.ok && state(r, 'faq_text') === 'ng' && /1 \/ 2問/.test(r.checks[0].detail) && /料金の目安/.test(r.checks[0].detail), r.checks[0]);
r = V.judge(job, page(faqHtml, ld(orgLd)), { status: 200, text: LLMS });
t('FAQPage のデータが無い：ng', !r.ok && state(r, 'faq_ld') === 'ng');
r = V.judge(job, page(faqHtml, ld(faqLd) + ld(orgLd) + ld({ '@context': 'https://schema.org', '@type': 'LocalBusiness', name: '別の名前' })), { status: 200, text: LLMS });
t('お店の情報が2つ：warn（二重）・全体は ok', r.ok && state(r, 'org') === 'warn' && /2つ/.test(r.checks.find((c) => c.key === 'org').detail));
r = V.judge(job, page(faqHtml, ld(faqLd) + ld(orgLd) + '<script type="application/ld+json">{"@type": "FAQPage",</script>'), { status: 200, text: LLMS });
t('読めない JSON-LD：ng', !r.ok && state(r, 'ld_broken') === 'ng');
r = V.judge(job, page(faqHtml, ld(faqLd) + ld(orgLd)), { status: 404, text: '' });
t('llms.txt が開けない：ng', !r.ok && state(r, 'llms') === 'ng' && /404/.test(r.checks.find((c) => c.key === 'llms').detail));
r = V.judge(job, page(faqHtml, ld(faqLd) + ld(orgLd)), { status: 200, text: '# 別の内容' });
t('llms.txt の中身が違う：warn・全体は ok', r.ok && state(r, 'llms') === 'warn');
r = V.judge(job, { status: 404, html: '' }, null);
t('ページが無い（404）：ng だけ', !r.ok && r.checks.length === 1 && /404/.test(r.checks[0].detail));
r = V.judge(job, page(faqHtml, ld({ '@context': 'https://schema.org', '@graph': [faqLd, orgLd] })), { status: 200, text: LLMS });
t('@graph の中の FAQPage・お店の情報も読む', r.ok && state(r, 'faq_ld') === 'ok' && state(r, 'org') === 'ok', r.checks);
const job0 = { url: job.url, files: { 'schema/organization.jsonld': job.files['schema/organization.jsonld'], 'MANIFEST.json': '{}' } };
r = V.judge(job0, page('<p>本文</p>', ld(orgLd)), null);
t('承認した FAQ が無いパッチ：FAQ の2項目は対象外・llms も対象外', r.ok && state(r, 'faq_text') === 'skip' && state(r, 'faq_ld') === 'skip' && state(r, 'llms') === 'skip');
t('ページの見える文字に script の中身を入れない', !/FAQPage/.test(V.visibleText(page('x', ld(faqLd)).html)));
const html = V.resultHtml({ ok: false, at: '2026-10-12T05:00:00Z', url: 'https://sample-salon.example/faq/', version: '1.3.0', checks: [{ key: 'x', label: '<b>x</b>', state: 'ng', detail: 'd' }] });
t('結果の表示：まだ入っていない・エスケープ', /まだ入っていないところがあります/.test(html) && !/<b>x<\/b>/.test(html));
// ④ の段階
const ent = { company: 'c', service: 's', at: '2026-10-07T01:00:00Z' };
const ans = (n) => Array.from({ length: n }, (_, i) => ({ prompt: 'q' + i, engine: 'google_aio', status: 'ok', mentioned: i < 2 ? 1 : 0, conditions: { engine: 'google_aio', search: true, location: 'JP', model: 'm' } }));
const base = { files: { 'MANIFEST.json': '{}' }, confirm: { entity: ent }, zipped: { at: '2026-10-08T00:00:00Z', version: '1.3.0', draft: false } };
const runs = [{ id: 'r1', created_at: '2026-10-07T02:00:00Z', summary: { answers: ans(9) } }];
let s = K.compute({ workspace: { orch: { lastJob: Object.assign({}, base, { verified: { at: '2026-10-12T00:00:00Z', ok: true } }) } }, runs, studioHref: '' });
t('④ 確かめて入っていれば済み・次は⑤', s.steps[3].state === 'done' && s.steps[4].state === 'current' && /入っている/.test(s.steps[3].detail));
s = K.compute({ workspace: { orch: { lastJob: Object.assign({}, base, { verified: { at: '2026-10-12T00:00:00Z', ok: false } }) } }, runs, studioHref: '' });
t('④ 入っていないところがあれば今のまま・次は「直して、もう一度確かめる」・#verify へ', s.steps[3].state === 'current' && /直して、もう一度確かめる/.test(s.next.title) && s.next.href === '#verify');
// 作ったときの ZIP の中身と比べる（あとで承認を変えても）
const snapJob = { url: job.url, files: { 'MANIFEST.json': '{}' }, zipped: { at: '2026-10-08T00:00:00Z', version: '1.3.0', draft: false, faq: Q, llms: LLMS, org_name: '株式会社サンプル' } };
r = V.judge(snapJob, page(faqHtml, ld(faqLd) + ld(orgLd)), { status: 200, text: LLMS });
t('作ったときの ZIP の中身（job.zipped）と比べる：いまの承認が0でも FAQ 2/2・llms 同じ', r.ok && state(r, 'faq_text') === 'ok' && /2 \/ 2問/.test(r.checks[0].detail) && state(r, 'llms') === 'ok', r.checks);
r = V.judge(Object.assign({}, snapJob, { zipped: Object.assign({}, snapJob.zipped, { draft: true }) }), page(faqHtml, ld(faqLd)), null);
t('下書きの ZIP の中身とは比べない（いまの承認で比べる）', state(r, 'faq_text') === 'skip');
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
